# Generated by Django 4.2.3 on 2024-09-04 00:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_certifyinginstitution_certificate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="time_stamp",
            field=models.DateTimeField(auto_now_add=True, max_length=500),
        ),
    ]
